# Generated by Django 3.0.1 on 2020-09-17 01:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyTable',
            fields=[
                ('api_key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('usage_limit', models.IntegerField(default=0)),
                ('total_usage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_ip', models.CharField(max_length=50)),
                ('request_id', models.CharField(default='request_id', max_length=32)),
                ('endpoint_name', models.TextField(blank=True, null=True)),
                ('request_url', models.TextField()),
                ('request_received_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_code', models.IntegerField()),
                ('response_json', models.TextField()),
                ('response_sent_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('api_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.KeyTable')),
            ],
        ),
    ]
